global:
  scrape_interval: 1m
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: [ 'localhost:9100' ]

  - job_name: 'server'
    static_configs:
      - targets: [ 'localhost:9200' ]